In [1]:
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

# Suppress warning and info messages from jax
import os  
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
# Random number generation

# Seed
key_x = random.PRNGKey(0)
key_y = random.PRNGKey(1)

# Create 2 n x n matrix of random numbers
n = 3
X = random.normal(key_x, (n, n), dtype=jnp.float32)
Y = random.normal(key_y, (n, n), dtype=jnp.float32)

print(X, "\n")
print(Y)

[[-0.3721109   0.26423115 -0.18252768]
 [-0.7368197   0.44973662 -0.1521442 ]
 [-0.67135346 -0.5908641   0.73168886]] 

[[ 0.690805   -0.48744103 -1.155789  ]
 [ 0.12108463  1.2010182  -0.5078766 ]
 [ 0.91568655  1.70968    -0.36749417]]


In [3]:
n = 3000
X = random.normal(key_x, (n, n), dtype=jnp.float32)
Y = random.normal(key_y, (n, n), dtype=jnp.float32)

# Time the execution of multiplying 2 matrices
# Jax by default is using asynchronous execution, block_until_ready() force synchronous
%timeit jnp.dot(X, Y).block_until_ready()

212 ms ± 15.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
# Using jit() to speed up functions
key = random.PRNGKey(42)

def selu(x, alpha=1.67, lmbda=1.05):
  return lmbda * jnp.where(x > 0, x, alpha * jnp.exp(x) - alpha)

# By default Jax tries to run on a GPU or TPU
# If not availible it falls back to the CPU
# jit() uses XLA (Accelerated Linear Algebra) for increased preformance
x = random.normal(key, (1000000,))
%timeit selu(x).block_until_ready()

# just-in-time (JIT) compilation decorator, sequences of operations can be optimized together and run at once
# Not all JAX code can be JIT compiled, as it requires array shapes to be static & known at compile time
selu_jit = jit(selu)
%timeit selu_jit(x).block_until_ready()

2.14 ms ± 61.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
288 µs ± 23.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
# Taking derivatives (gradients)

# Define function
def logistic_func(x):
  return jnp.sum(1.0 / (1.0 + jnp.exp(-x)))

# Generate inputs
x_small = jnp.arange(3.)
print(x_small)

# Create gradient of the function
derivative_fn = grad(logistic_func)

# Calculate gradient
print("\nGradient:\n",derivative_fn(x_small))

[0. 1. 2.]

Gradient:
 [0.25       0.19661197 0.10499357]


In [6]:
# vectorization - converting a matrix into a vector 

mat = random.normal(key, (150, 100))
batched_x = random.normal(key, (10, 100))

def apply_matrix(v):
  return jnp.dot(mat, v)

@jit
def vmap_batched_apply_matrix(v_batched):
  return vmap(apply_matrix)(v_batched)

print('\nAuto-vectorized with vmap:')
%timeit vmap_batched_apply_matrix(batched_x).block_until_ready()


Auto-vectorized with vmap:
23.3 µs ± 310 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
# Arrays
import numpy as np

# NumPy: mutable arrays
x = np.arange(10)
# can do x[0] = 1

# JAX: immutable arrays
x = jnp.arange(10)
# cannot do x[0] = 1

# instead can create a updated copy 
y = x.at[0].set(10)

print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[10  1  2  3  4  5  6  7  8  9]


In [8]:
# MLP Model

# A helper function to randomly initialize weights and biases
# for a dense neural network layer
def random_layer_params(m, n, key, scale=1e-2):
    w_key, b_key = random.split(key)
    return scale * random.normal(w_key, (n, m)), scale * random.normal(b_key, (n,))

# Initialize all layers for a fully-connected neural network with sizes "sizes"
def init_network_params(sizes, key):
    keys = random.split(key, len(sizes))
    return [random_layer_params(m, n, k) for m, n, k in zip(sizes[:-1], sizes[1:], keys)]

# Hyperparameters
# layer_sizes = [784, 512, 512, 10]
layer_sizes = [784, 100, 10]
step_size = 0.01
num_epochs = 10
batch_size = 128
n_targets = 10
params = init_network_params(layer_sizes, random.PRNGKey(0))

In [9]:
# Define relu and prediction function

from jax.scipy.special import logsumexp

def relu(x):
  return jnp.maximum(0, x)

def predict(params, image):
  # per-example predictions
  activations = image
  for w, b in params[:-1]:
    outputs = jnp.dot(w, activations) + b
    activations = relu(outputs)
  
  final_w, final_b = params[-1]
  logits = jnp.dot(final_w, activations) + final_b
  return logits - logsumexp(logits)

# Running on a single example image
random_flattened_image = random.normal(random.PRNGKey(1), (28 * 28,))
print(f"Image Shape: {random_flattened_image.shape}")

preds = predict(params, random_flattened_image)
print(preds.shape)

Image Shape: (784,)
(10,)


In [10]:
# Define batch of images - 10 images of 28x28
random_flattened_images = random.normal(random.PRNGKey(1), (10, 28 * 28))

# Make a batched version of the `predict` function
batched_predict = vmap(predict, in_axes=(None, 0))

# `batched_predict` has the same call signature as `predict`
batched_preds = batched_predict(params, random_flattened_images)
print(batched_preds.shape)

(10, 10)


In [11]:
# Define utility functions

# Create one hot encoding of the output
def one_hot(x, k, dtype=jnp.float32):
  """Create a one-hot encoding of x of size k."""
  return jnp.array(x[:, None] == jnp.arange(k), dtype)

# Test accuracy 
def accuracy(params, images, targets):
  target_class = jnp.argmax(targets, axis=1)
  predicted_class = jnp.argmax(batched_predict(params, images), axis=1)
  return jnp.mean(predicted_class == target_class)

# Find loss
def loss(params, images, targets):
  preds = batched_predict(params, images)
  return -jnp.mean(preds * targets)

# Backpropagration
@jit
def update(params, x, y):
  grads = grad(loss)(params, x, y)
  return [(w - step_size * dw, b - step_size * db)
          for (w, b), (dw, db) in zip(params, grads)]

In [12]:
# Load and Create Datasets
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

import tensorflow as tf
import tensorflow_datasets as tfds

print(f"CUDA_VISIBLE_DEVICES = {os.environ['CUDA_VISIBLE_DEVICES']}")
print(f"TF_CPP_MIN_LOG_LEVEL = {os.environ['TF_CPP_MIN_LOG_LEVEL']}")

# List GPUs availible
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
print("Num CPUs Available: ", len(tf.config.list_physical_devices('CPU')))

from tensorflow.python.client import device_lib
print("\n", device_lib.list_local_devices(), '\n')

data_dir = './datasets'

# Fetch full datasets for evaluation
# tfds.load returns tf.Tensors (or tf.data.Datasets if batch_size != -1)
# You can convert them to NumPy arrays (or iterables of NumPy arrays) with tfds.dataset_as_numpy
mnist_data, info = tfds.load(name="mnist", batch_size=-1, data_dir=data_dir, with_info=True)

mnist_data = tfds.as_numpy(mnist_data)
train_data, test_data = mnist_data['train'], mnist_data['test']
num_labels = info.features['label'].num_classes
h, w, c = info.features['image'].shape
num_pixels = h * w * c

# # Full train set
train_images, train_labels = train_data['image'], train_data['label']
train_images = jnp.reshape(train_images, (len(train_images), num_pixels))
train_labels = one_hot(train_labels, num_labels)

# # Full test set
test_images, test_labels = test_data['image'], test_data['label']
test_images = jnp.reshape(test_images, (len(test_images), num_pixels))
test_labels = one_hot(test_labels, num_labels)

print('Train:', train_images.shape, train_labels.shape)
print('Test:', test_images.shape, test_labels.shape)

2022-11-06 12:05:39.690009: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
/home/urban/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


CUDA_VISIBLE_DEVICES = -1
TF_CPP_MIN_LOG_LEVEL = 2
Num GPUs Available:  0
Num CPUs Available:  1

 [name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 9808717370502298304
xla_global_id: -1
] 



2022-11-06 12:05:42.717410: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


Train: (60000, 784) (60000, 10)
Test: (10000, 784) (10000, 10)


In [13]:
import time

def get_train_batches():
  
    # as_supervised=True gives us the (image, label) as a tuple instead of a dict
    ds = tfds.load(name='mnist', split='train', as_supervised=True, data_dir=data_dir)
    
    # You can build up an arbitrary tf.data input pipeline
    ds = ds.batch(batch_size).prefetch(1)
    
    # tfds.dataset_as_numpy converts the tf.data.Dataset into an iterable of NumPy arrays
    return tfds.as_numpy(ds)

def train(params):
    for epoch in range(num_epochs):
        
        start_time = time.time()
        for x, y in get_train_batches():
            x = jnp.reshape(x, (len(x), num_pixels))
            y = one_hot(y, num_labels)
            params = update(params, x, y)
        
        epoch_time = time.time() - start_time

        train_acc = accuracy(params, train_images, train_labels)
        test_acc = accuracy(params, test_images, test_labels)
        print("Epoch {} in {:0.2f} sec".format(epoch, epoch_time))
        print("Training set accuracy {}".format(train_acc))
        print("Test set accuracy {}".format(test_acc))

# Train Model
train(params)

Epoch 0 in 2.08 sec
Training set accuracy 0.9381499886512756
Test set accuracy 0.9386000037193298
Epoch 1 in 1.67 sec
Training set accuracy 0.9552333354949951
Test set accuracy 0.952299952507019
Epoch 2 in 1.55 sec
Training set accuracy 0.9646000266075134
Test set accuracy 0.9587999582290649
Epoch 3 in 1.55 sec
Training set accuracy 0.9693500399589539
Test set accuracy 0.9626999497413635
Epoch 4 in 1.55 sec
Training set accuracy 0.9730333685874939
Test set accuracy 0.9646999835968018
Epoch 5 in 1.64 sec
Training set accuracy 0.9758833646774292
Test set accuracy 0.9659000039100647
Epoch 6 in 1.57 sec
Training set accuracy 0.9785333275794983
Test set accuracy 0.9667999744415283
Epoch 7 in 1.67 sec
Training set accuracy 0.9805499911308289
Test set accuracy 0.9669999480247498
Epoch 8 in 1.60 sec
Training set accuracy 0.9822333455085754
Test set accuracy 0.967799961566925
Epoch 9 in 1.55 sec
Training set accuracy 0.9839333295822144
Test set accuracy 0.968999981880188


In [14]:
# Load MNIST Using Keras
import keras

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

print('Train:', x_train.shape, y_train.shape)
print('Test:', x_test.shape, y_test.shape)

Train: (60000, 28, 28) (60000,)
Test: (10000, 28, 28) (10000,)


In [22]:
# =============================================
# using adam optimizer
# =============================================

import numpy as np
from jax import value_and_grad
from jax.scipy.special import logsumexp
import optax

key = random.PRNGKey(1)

@jit
def update_adam(params, x, y, opt_state):
    """ Compute the gradient for a batch and update the parameters """
    
    grads = grad(loss)(params, x, y)
    updates, opt_state = optimizer.update(grads, opt_state)
    params = optax.apply_updates(params, updates)
    
    return params, opt_state

# Defining an optimizer in Jax
learning_rate = 1e-3
optimizer = optax.adam(learning_rate)

# Initialize parameters of the model + optimizer.
opt_state = optimizer.init(params)

In [23]:
for epoch in range(num_epochs):

    start_time = time.time()
    
    for x, y in get_train_batches():
        x = jnp.reshape(x, (len(x), num_pixels))
        y = one_hot(y, num_labels)
        
        params, opt_state = update_adam(params, x, y, opt_state)

    epoch_time = time.time() - start_time

    train_acc = accuracy(params, train_images, train_labels)
    test_acc = accuracy(params, test_images, test_labels)
    print("Epoch {} in {:0.2f} sec".format(epoch, epoch_time))
    print("Training set accuracy {}".format(train_acc))
    print("Test set accuracy {}".format(test_acc))

Epoch 0 in 2.21 sec
Training set accuracy 0.9605333209037781
Test set accuracy 0.955299973487854
Epoch 1 in 1.50 sec
Training set accuracy 0.9616000056266785
Test set accuracy 0.9536999464035034
Epoch 2 in 1.53 sec
Training set accuracy 0.9693166613578796
Test set accuracy 0.9611999988555908
Epoch 3 in 1.51 sec
Training set accuracy 0.9732833504676819
Test set accuracy 0.9621999859809875
Epoch 4 in 1.55 sec
Training set accuracy 0.9647166728973389
Test set accuracy 0.9541999697685242
Epoch 5 in 1.52 sec
Training set accuracy 0.9755499958992004
Test set accuracy 0.9617999792098999
Epoch 6 in 1.52 sec
Training set accuracy 0.9752333164215088
Test set accuracy 0.9569000005722046
Epoch 7 in 1.50 sec
Training set accuracy 0.9808833599090576
Test set accuracy 0.9648999571800232
Epoch 8 in 1.74 sec
Training set accuracy 0.9796333312988281
Test set accuracy 0.9652999639511108
Epoch 9 in 1.53 sec
Training set accuracy 0.9731166958808899
Test set accuracy 0.9592999815940857
